# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "cab0c0918329fc7126707d242a63ed79"
name = "checkout-custom-function"
handle = "checkout-custom-function"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_discounts"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[pos]
embedded = false
